image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

services:
  - docker

install:
  - docker-compose up &
  - sleep 240
  - java -jar ./artifacts/app-deadline.jar &
  - chmod +x gradlew

build_script:
  - ./gradlew test --info -Dselenide.headless=true
